services:
  mysql:
    image: mysql:8.0
    container_name: cinenight-mysql
    restart: always
    environment:
      MYSQL_DATABASE: cinenight
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cinenight-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: cinenight-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${DB_PASSWORD}
      TMDB_API_KEY: ${TMDB_API_KEY}
      APP_FRONTEND_BASE_URL: https://cinenight.tech
      MAIL_HOST: smtp.gmail.com
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    networks:
      - cinenight-net

  frontend:
    build: ./frontend
    container_name: cinenight-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cinenight-net

volumes:
  mysql_data:

networks:
  cinenight-net:
    driver: bridge