server:
  port: 8080

spring:
  config:
    import: optional:file:env/backend.local.properties
  datasource:
    url: jdbc:mysql://localhost:3306/cinenight?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  cache:
    type: caffeine

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail.smtp.auth: ${MAIL_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_STARTTLS:false}

logging.level:
  org.springframework.mail: DEBUG
  com.sun.mail: DEBUG

app:
  frontend:
    base-url: ${APP_FRONTEND_BASE_URL:http://localhost:5173}
  mail:
    from: "CineNight <esadzahid57@gmail.com>"

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3
  image-base: https://image.tmdb.org/t/p