server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinenight?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

logging.level:
  org.springframework.security: INFO
